name: Noetic 22.04 ROS CI Docker build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: git clone git@github.com:lucasw/screen_grab
        uses: actions/checkout@v4
        with:
          path: catkin_ws/src/screen_grab

      - name: docker build ubuntu 22.04
        run: |
          cd catkin_ws/src/screen_grab
          docker build . -t ubuntu_2204
